---
title: "Scores Radar By Task"
llms-description: Radar plot comparing multiple models across headline metrics from different evals.
reference: "inspect_viz.view"
datafile: "radar_by_task.parquet"
---

## Overview

The `scores_radar_by_task()`function renders a radar chart for comparing headline metrics from different tasks across multiple models. This is useful for comparing the relative performance of models across different tasks.

```{python}
from inspect_viz import Data
from inspect_viz.view import scores_radar_by_task

evals = Data.from_file("radar_by_task.parquet")
scores_radar_by_task(evals)
```

The scores plotted on this radar chart have been normalized using percentile ranking, which means each score represents the model's relative performance compared to all other models in the dataset. Specifically, a score of 0.5 indicates that the model performed better than 50% of the other models. Absolute scores are displayed in the tooltips.

You can use `scores_radar_by_task_df()` to produce data with min-max normalization, omit normalization entirely, or invert the scores for tasks where lower scores are better.

## Data Preparation

{{< include _data_preparation_scores_radar_by_task.md >}}

## Function Reference

### scores_radar_by_task {reference="scores_radar_by_task"}

### scores_radar_by_task_df {reference="scores_radar_by_task_df"}

## Implementation

The [Scores Radar By Task](examples/inspect/scores-radar-by-task/index.qmd) example demonstrates how this view was implemented using lower level plotting components.
