---
reference: inspect_viz.mark
description: Plot marks (charts, annotations, etc.).
---

## Basic

### dot
### dot_x
### dot_y
### circle
### hexagon
### line
### line_x
### line_y
### area
### area_x
### area_y
### bar_x
### bar_y
### heatmap

## Statistical

### density
### density_x
### density_y
### contour
### regression_y
### error_bar_x
### error_bar_y

## Grid

### cell
### cell_x
### cell_y
### grid_x
### grid_y
### grid_fx
### grid_fy
### hexbin
### hexgrid
### waffle_x
### waffle_y

## Specialized

### raster
### raster_tile
### vector
### vector_x
### vector_y
### spike
### arrow
### link
### delaunay_link
### delaunay_mesh
### voronoi
### voronoi_mesh
### hull
### dense_line

## Decoration

### title
### frame
### axis_x
### axis_y
### axis_fx
### axis_fy
### rule_x
### rule_y
### tick_x
### tick_y
### rect
### rect_x
### rect_y
### text
### text_x
### text_y
### image

## Geographic

### geo
### graticule
### sphere

## Types

### Mark
### MarkOptions
### Marks
### Title
### Channel
### ChannelSpec
### ChannelIntervalSpec
### ChannelWithInterval
### ChannelWithScale
### ChannelName
### TipOptions
### TipPointer
### Curve
### Symbol
### Marker
### Interpolate
### FrameAnchor
### LineAnchor
### TextOverflow
### TextStyles